export function renderHomePage(): string {
  return `<!doctype html>
<html lang="ko">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="description" content="지자체 보고·결재 요청과 결정권자 일정을 하나로 연결하는 업무관리 서비스">
  <title>리포트온 | 지자체 보고·결재 예약관리</title>
  <link rel="icon" href="/favicon.ico">
  <style>
    :root{--navy:#12233f;--blue:#2563eb;--blue2:#1d4ed8;--sky:#eaf2ff;--ink:#172033;--muted:#617089;--line:#dce5f0;--paper:#fff;--soft:#f5f8fc;--green:#0f9f6e;--orange:#f97316}
    *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#fff;color:var(--ink);font-family:Pretendard,"Noto Sans KR","Apple SD Gothic Neo",Arial,sans-serif;word-break:keep-all}a{text-decoration:none;color:inherit}.wrap{width:min(1180px,90%);margin:auto}
    .top{position:sticky;top:0;z-index:50;border-bottom:1px solid rgba(220,229,240,.9);background:rgba(255,255,255,.94);backdrop-filter:blur(14px)}.top-in{height:72px;display:flex;align-items:center;gap:34px}.brand{display:flex;align-items:center;gap:11px;font-weight:900;letter-spacing:-.04em}.mark{display:grid;place-items:center;width:36px;height:36px;border-radius:11px;background:linear-gradient(145deg,#3777f6,#1848c7);color:#fff;box-shadow:0 8px 20px rgba(37,99,235,.25)}.brand small{display:block;margin-top:1px;color:#78869a;font-size:10px;font-weight:700;letter-spacing:0}.nav{display:flex;gap:26px;margin-left:auto;color:#526078;font-size:14px;font-weight:700}.nav a:hover{color:var(--blue)}.login{display:inline-flex;align-items:center;justify-content:center;height:42px;padding:0 20px;border-radius:9px;background:var(--navy);color:#fff;font-size:14px;font-weight:800;box-shadow:0 7px 18px rgba(18,35,63,.18)}
    .hero{overflow:hidden;padding:88px 0 84px;background:radial-gradient(circle at 83% 20%,#dceaff 0,transparent 34%),linear-gradient(180deg,#f8fbff,#fff)}.hero-grid{display:grid;grid-template-columns:1.02fr .98fr;align-items:center;gap:58px}.eyebrow{display:inline-flex;align-items:center;gap:8px;padding:7px 12px;border-radius:999px;background:#e8f0ff;color:var(--blue2);font-size:13px;font-weight:800}.eyebrow:before{content:"";width:7px;height:7px;border-radius:50%;background:var(--blue)}h1{margin:22px 0 20px;font-size:clamp(38px,5vw,62px);line-height:1.12;letter-spacing:-.055em}.hero h1 em{color:var(--blue);font-style:normal}.lead{max-width:620px;margin:0;color:var(--muted);font-size:18px;line-height:1.8}.hero-actions{display:flex;align-items:center;gap:12px;margin-top:32px}.primary,.outline{display:inline-flex;align-items:center;justify-content:center;height:52px;padding:0 24px;border-radius:10px;font-size:15px;font-weight:850}.primary{background:var(--blue);color:#fff;box-shadow:0 12px 28px rgba(37,99,235,.25)}.outline{border:1px solid #cdd8e7;background:#fff;color:#334155}.micro{margin-top:16px;color:#8190a5;font-size:12px}
    .product{position:relative;padding:15px;border:1px solid #cddbf0;border-radius:24px;background:rgba(255,255,255,.8);box-shadow:0 28px 70px rgba(41,67,107,.18)}.screen{overflow:hidden;border-radius:15px;background:#f4f7fb}.screen-head{display:flex;align-items:center;gap:8px;height:48px;padding:0 16px;background:var(--navy);color:#fff;font-size:12px;font-weight:800}.screen-head i{width:9px;height:9px;border-radius:50%;background:#4ade80}.screen-body{display:grid;grid-template-columns:110px 1fr;min-height:355px}.side{padding:18px 10px;background:#fff}.side b{display:block;margin-bottom:16px;font-size:11px}.side span{display:block;margin:8px 0;padding:9px;border-radius:7px;background:#edf3ff;color:#285aca;font-size:9px;font-weight:800}.dash{padding:19px}.dash h3{margin:0 0 14px;font-size:15px}.stat-row{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.mini-card{padding:12px;border:1px solid #dfe7f1;border-radius:9px;background:#fff}.mini-card small{color:#65758c;font-size:8px}.mini-card strong{display:block;margin-top:6px;font-size:19px}.queue{margin-top:10px;overflow:hidden;border:1px solid #dfe7f1;border-radius:9px;background:#fff}.queue-title{padding:11px;border-bottom:1px solid #e5ebf3;font-size:10px;font-weight:850}.row{display:grid;grid-template-columns:55px 1fr 54px;align-items:center;gap:7px;padding:11px;border-bottom:1px solid #edf1f6;font-size:8px}.row:last-child{border:0}.tag{padding:4px 5px;border-radius:999px;background:#fff0e7;color:#d64d0a;text-align:center;font-weight:800}.state{padding:5px;border-radius:999px;background:#eaf8f1;color:#087b55;text-align:center}
    .trust{border-block:1px solid #e7edf5;background:#fbfcfe}.trust-in{display:grid;grid-template-columns:1.15fr repeat(3,1fr);align-items:center;min-height:105px;gap:20px}.trust b{font-size:15px}.trust-item{padding-left:22px;border-left:1px solid #dfe7f1}.trust-item strong{display:block;font-size:19px}.trust-item span{display:block;margin-top:5px;color:#7b889b;font-size:12px}
    section.block{padding:100px 0}.section-head{max-width:720px;margin:0 auto 48px;text-align:center}.kicker{color:var(--blue);font-size:13px;font-weight:900;letter-spacing:.08em}.section-head h2{margin:12px 0 14px;font-size:clamp(29px,4vw,42px);letter-spacing:-.045em}.section-head p{margin:0;color:var(--muted);line-height:1.75}.benefits{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.benefit{position:relative;min-height:260px;padding:28px;border:1px solid var(--line);border-radius:18px;background:#fff;box-shadow:0 12px 35px rgba(37,57,87,.07)}.benefit:first-child{background:var(--navy);color:#fff}.icon{display:grid;place-items:center;width:48px;height:48px;border-radius:13px;background:#eaf2ff;color:var(--blue);font-size:22px}.benefit:first-child .icon{background:rgba(255,255,255,.13);color:#fff}.benefit h3{margin:23px 0 12px;font-size:20px}.benefit p{margin:0;color:#66758b;font-size:14px;line-height:1.75}.benefit:first-child p{color:#c9d5e7}.gain{display:inline-block;margin-top:20px;color:var(--blue);font-size:12px;font-weight:850}.benefit:first-child .gain{color:#7db0ff}
    .flow-bg{background:var(--soft)}.flow{display:grid;grid-template-columns:repeat(5,1fr);gap:12px}.step{position:relative;padding:23px 19px;border:1px solid var(--line);border-radius:14px;background:#fff}.step:not(:last-child):after{content:"→";position:absolute;right:-17px;top:50%;z-index:2;color:#8ea1bb;font-weight:900}.step i{display:block;color:var(--blue);font-size:12px;font-style:normal;font-weight:900}.step strong{display:block;margin:13px 0 8px;font-size:16px}.step p{margin:0;color:#728198;font-size:12px;line-height:1.65}
    .feature-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px}.feature{display:flex;gap:18px;padding:25px;border:1px solid var(--line);border-radius:15px}.feature .icon{flex:none;width:42px;height:42px;font-size:18px}.feature h3{margin:0 0 7px;font-size:17px}.feature p{margin:0;color:#6b7a90;font-size:13px;line-height:1.7}
    .pricing{padding:90px 0;background:linear-gradient(145deg,#10203a,#192f51);color:#fff}.price-grid{display:grid;grid-template-columns:1fr 430px;align-items:center;gap:70px}.pricing h2{margin:10px 0 16px;font-size:39px;letter-spacing:-.045em}.pricing .copy{color:#bdcbe0;line-height:1.8}.price-card{padding:30px;border:1px solid rgba(255,255,255,.18);border-radius:20px;background:#fff;color:var(--ink);box-shadow:0 25px 60px rgba(0,0,0,.24)}.price-card>span{color:var(--blue);font-size:12px;font-weight:900}.price-main{display:flex;align-items:end;gap:7px;margin:12px 0 5px}.price-main strong{font-size:49px;letter-spacing:-.05em}.price-main b{padding-bottom:9px;color:#67768b}.setup{padding-bottom:20px;border-bottom:1px solid #e3e9f1;color:#6a7890;font-size:13px}.price-card ul{margin:22px 0;padding:0;list-style:none}.price-card li{margin:12px 0;font-size:14px}.price-card li:before{content:"✓";margin-right:9px;color:var(--green);font-weight:900}.price-card .primary{width:100%}
    .cta{padding:84px 0;text-align:center}.cta-box{padding:55px 28px;border-radius:24px;background:#edf4ff}.cta h2{margin:0 0 13px;font-size:34px}.cta p{margin:0 0 27px;color:#62728a}.footer{padding:38px 0;border-top:1px solid #e3e9f1;background:#f8fafc;color:#718096;font-size:12px}.footer-in{display:grid;grid-template-columns:210px 1fr auto;align-items:start;gap:34px}.footer .brand{color:var(--ink);font-size:15px}.company{display:flex;flex-wrap:wrap;gap:7px 18px;line-height:1.65}.company strong{width:100%;color:#344258;font-size:13px}.company a{color:#52657f}.company a:hover{color:var(--blue)}.copyright{color:#8a97aa;white-space:nowrap;line-height:1.65;text-align:right}
    @media(max-width:900px){.nav{display:none}.hero{padding-top:58px}.hero-grid,.price-grid{grid-template-columns:1fr}.product{max-width:620px;transform:none}.benefits{grid-template-columns:1fr}.flow{grid-template-columns:1fr 1fr}.step:after{display:none}.trust-in{grid-template-columns:1fr 1fr;padding:24px 0}.trust-item{padding:0;border:0}.feature-grid{grid-template-columns:1fr}.price-card{max-width:520px}}
    @media(max-width:560px){.wrap{width:92%}.top-in{height:64px}.brand-text small{display:none}.login{height:38px;padding:0 15px}.hero{padding:45px 0 60px}.hero-grid{gap:40px}h1{font-size:38px}.lead{font-size:16px}.hero-actions{align-items:stretch;flex-direction:column}.screen-body{grid-template-columns:76px 1fr}.side{padding-inline:6px}.stat-row{grid-template-columns:1fr}.mini-card:nth-child(n+2){display:none}.trust-in,.flow{grid-template-columns:1fr}.trust-item{padding-top:10px}.feature{padding:20px}.price-grid{gap:35px}.price-card{padding:23px}.footer-in{grid-template-columns:1fr}.copyright{text-align:left}}
  </style>
</head>
<body>
  <header class="top"><div class="wrap top-in"><a class="brand" href="/" aria-label="리포트온 홈"><span class="mark">R</span><span class="brand-text">리포트온<small>보고·결재 예약관리</small></span></a><nav class="nav" aria-label="주요 메뉴"><a href="#benefit">도입 효과</a><a href="#flow">업무 흐름</a><a href="#feature">주요 기능</a><a href="#price">이용 요금</a></nav><a class="login" href="/app">로그인</a></div></header>
  <main>
    <section class="hero"><div class="wrap hero-grid"><div><span class="eyebrow">지자체 의사결정 업무를 더 빠르게</span><h1>보고 요청부터 일정 확정까지,<br><em>한 흐름으로 연결합니다</em></h1><p class="lead">전화, 메신저, 문서로 흩어진 보고·결재 예약 업무를 하나의 시스템으로 통합하세요. 요청자는 진행 상황을 확인하고, 부서장과 비서실은 필요한 안건에 집중할 수 있습니다.</p><div class="hero-actions"><a class="primary" href="/app">업무 시스템 로그인 →</a><a class="outline" href="#benefit">도입 효과 보기</a></div><p class="micro">지자체별 독립 운영 · 역할 기반 권한 · 실시간 상태 확인</p></div><div class="product" aria-label="서비스 화면 예시"><div class="screen"><div class="screen-head"><i></i> 보고·결재 예약관리 <span style="margin-left:auto;opacity:.72">실시간 연결</span></div><div class="screen-body"><div class="side"><b>업무 홈</b><span>내 요청 현황</span><span>알림 내역</span><span>결정권자 일정</span></div><div class="dash"><h3>오늘의 보고 현황</h3><div class="stat-row"><div class="mini-card"><small>요청 접수</small><strong>12</strong></div><div class="mini-card"><small>비서실 검토</small><strong>5</strong></div><div class="mini-card"><small>예약 확정</small><strong>3</strong></div></div><div class="queue"><div class="queue-title">보고 요청 목록</div><div class="row"><span class="tag">긴급</span><b>현안 대응 계획 보고</b><span class="state">검토 중</span></div><div class="row"><span class="tag">중요</span><b>복지사업 추진안 결재</b><span class="state">이관</span></div><div class="row"><span class="tag">일반</span><b>주간 업무계획 보고</b><span class="state">접수</span></div></div></div></div></div></div></div></section>
    <div class="trust"><div class="wrap trust-in"><b>행정 업무의 병목을<br>눈에 보이는 흐름으로</b><div class="trust-item"><strong>한눈에</strong><span>안건 상태와 담당자 확인</span></div><div class="trust-item"><strong>실시간</strong><span>상태 변경 및 이메일 알림</span></div><div class="trust-item"><strong>역할별</strong><span>필요한 업무만 정확하게</span></div></div></div>
    <section class="block" id="benefit"><div class="wrap"><div class="section-head"><span class="kicker">WHY REPORTON</span><h2>지자체가 얻는 변화는 분명합니다</h2><p>새로운 절차를 더하는 시스템이 아니라, 이미 하고 있는 보고·결재 업무의 대기와 확인 비용을 줄이는 시스템입니다.</p></div><div class="benefits"><article class="benefit"><span class="icon">⏱</span><h3>보고 대기시간 단축</h3><p>결정권자의 보고 가능 시간과 요청 우선순위를 한곳에서 조정해 불필요한 전화 확인과 문 앞 대기를 줄입니다.</p><span class="gain">→ 담당자는 본연의 행정 업무에 집중</span></article><article class="benefit"><span class="icon">◎</span><h3>누락 없는 책임 행정</h3><p>누가 요청했고 어디까지 검토됐는지 상태와 이력을 남겨 구두 전달 과정에서 생기는 누락과 책임 공백을 예방합니다.</p><span class="gain">→ 요청·검토·이관 과정의 투명성 향상</span></article><article class="benefit"><span class="icon">↗</span><h3>긴급 현안의 빠른 판단</h3><p>일반·중요·긴급·즉시 안건을 구분하고 긴급 안건을 대기열에 반영해 우선 대응이 필요한 사안을 놓치지 않습니다.</p><span class="gain">→ 재난·민원·현안 대응 속도 향상</span></article></div></div></section>
    <section class="block flow-bg" id="flow"><div class="wrap"><div class="section-head"><span class="kicker">CONNECTED WORKFLOW</span><h2>요청부터 결정까지 끊김 없이</h2><p>조직의 기존 결재선을 반영한 역할별 업무 화면으로 각 담당자가 다음 할 일을 명확하게 확인합니다.</p></div><div class="flow"><article class="step"><i>01 요청자</i><strong>안건 등록</strong><p>긴급도, 보고 대상, 희망 시간과 자료를 등록합니다.</p></article><article class="step"><i>02 부서장</i><strong>내용 검토</strong><p>안건을 확인해 상신하거나 사유와 함께 반려합니다.</p></article><article class="step"><i>03 비서실</i><strong>대기열 배정</strong><p>우선순위와 결정권자 일정을 고려해 순서를 조정합니다.</p></article><article class="step"><i>04 결정권자</i><strong>보고·결재</strong><p>정리된 안건과 첨부자료를 바탕으로 판단합니다.</p></article><article class="step"><i>05 전체</i><strong>결과 공유</strong><p>변경 상태와 결과를 실시간 화면과 이메일로 확인합니다.</p></article></div></div></section>
    <section class="block" id="feature"><div class="wrap"><div class="section-head"><span class="kicker">CORE FEATURES</span><h2>행정 조직을 고려한 핵심 기능</h2></div><div class="feature-grid"><article class="feature"><span class="icon">▦</span><div><h3>결정권자 24시간 일정관리</h3><p>10분·30분 간격으로 보고 가능 시간을 지정하고 마우스로 일정 범위를 조정합니다.</p></div></article><article class="feature"><span class="icon">⇅</span><div><h3>우선순위 기반 통합 대기열</h3><p>긴급도와 검토 상태에 따라 요청을 분류하고 비서실에서 보고 순서를 관리합니다.</p></div></article><article class="feature"><span class="icon">●</span><div><h3>실시간 현황과 알림</h3><p>요청 상태가 바뀌면 화면의 현황이 연결되고 담당자 이메일로 변경 사실을 안내합니다.</p></div></article><article class="feature"><span class="icon">⌁</span><div><h3>지자체 조직·역할별 권한</h3><p>요청자, 부서장, 국장, 비서실, 일정관리자, 의사결정권자별 화면과 권한을 제공합니다.</p></div></article><article class="feature"><span class="icon">✓</span><div><h3>검토·반려 이력 관리</h3><p>확인 전 수정, 검토 후 잠금, 반려사유 전달 등 실제 행정 검토 절차를 반영합니다.</p></div></article><article class="feature"><span class="icon">▣</span><div><h3>첨부자료 통합 관리</h3><p>한글·MS Office·PDF 자료를 요청과 함께 관리하고 권한이 있는 사용자가 내려받습니다.</p></div></article></div></div></section>
    <section class="pricing" id="price"><div class="wrap price-grid"><div><span class="kicker" style="color:#7fb0ff">SIMPLE PRICING</span><h2>작은 비용으로 시작하는<br>지자체 업무 혁신</h2><p class="copy">별도 대규모 시스템 구축 부담 없이 필요한 기능부터 빠르게 도입하세요. 지자체 조직과 기본코드 설정을 지원합니다.</p></div><article class="price-card"><span>지자체 단위 이용 요금</span><div class="price-main"><strong>월 30,000원</strong><b>/ 지자체</b></div><p class="setup">초기 설치비 500,000원</p><ul><li>역할별 사용자 및 권한 관리</li><li>보고·결재 요청과 검토 흐름</li><li>비서실 대기열 및 결정권자 일정</li><li>실시간 현황과 이메일 알림</li></ul><a class="primary" href="/app">로그인하여 시작하기</a></article></div></section>
    <section class="cta"><div class="wrap cta-box"><h2>더 빠른 보고, 더 명확한 의사결정</h2><p>흩어진 보고 예약 업무를 하나의 행정 흐름으로 연결해 보세요.</p><a class="primary" href="/app">리포트온 로그인 →</a></div></section>
  </main>
  <footer class="footer"><div class="wrap footer-in"><span class="brand"><span class="mark" style="width:28px;height:28px;border-radius:8px">R</span>리포트온</span><div class="company"><strong>(주)모노라마</strong><span>대표 김창호</span><span>사업자등록번호 277-86-00185</span><span>서울특별시 강남구 영동대로71길 16, 3층 (06187)</span><span>대표전화 <a href="tel:0269254083">02-6925-4083</a></span><span>팩스 0504-255-4082</span><span>이메일 <a href="mailto:kimch@monorama.kr">kimch@monorama.kr</a></span></div><div class="copyright">지자체 보고·결재 예약관리 서비스<br>© 2026 MONORAMA Co., Ltd.</div></div></footer>
</body>
</html>`;
}
